function createfigure(X1, YMatrix1, YData1, XData1)
%CREATEFIGURE(X1, YMatrix1, YData1, XData1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata

%  Auto-generated by MATLAB on 05-Feb-2022 08:22:06

% Create figure
figure1 = figure('PaperUnits','normalized','PaperSize',[1 1],...
    'NumberTitle','off',...
    'Name','Figure',...
    'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','Upper payoff frontier','Color',[1 0 0]);
set(plot1(2),'DisplayName','Lower payoff frontier','Color',[0 0 1]);

% Create patch
patch('DisplayName','No information optimal region','YData',YData1,...
    'XData',XData1,...
    'FaceColor',[0 1 0]);

% Create ylabel
ylabel({'Submodularity parameter, $\beta$'},'Interpreter','latex');

% Create xlabel
xlabel({'Number of agents, $n$'},'Interpreter','latex');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[2 20]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-30 30]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',18,'XTick',[2 6 10 14 18 20]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.146875 0.75357142857143 0.452678571428571 0.147619047619048],...
    'FontSize',16,...
    'EdgeColor',[1 1 1]);

